version : 3

tasks:
  build:
    cmds:
      - go build -o bin/app cmd/main.go
  run:
    cmds:
      - task build
      - ./bin/app
  deps:
    cmds:
      - go mod download
  docker-build:
    cmds:
      - docker build -t geass .
  docker-run:
    cmds:
      - docker run -p 8080:8080 -t geass